### ISSUE TITLE
Slow var1 simulations 

### ISSUE THREAD

**Issue by azheng25** [EconForge/Dolo.jl#100]
Dolo has slow simulations of var1 processes: `sim_armc = Dolo.simulate(model,dr;N=500,T=500)` takes almost five minutes. Discretizing the var1 into a mc first and then using a simulated MC as an input takes only a few seconds.

**Comment by albop** [comment]
Is it also true if you do:  `Dolo.simulate(model.exogenous, dr ;N=500,T=500)` ? when model.exogenous is a VAR1 ? If so, that's really problematic, but should be easy to fix.

**Comment by azheng25** [comment]
Yes there is a similar problem. When I do `@time Dolo.simulate(model.exogenous,500,500)` it takes 214 seconds when model.exogenous is a VAR1.

**Comment by albop** [comment]
@azheng25 : how big is the model you are using ? Does it have many shocks ?  Can you copy/paste the exogenous section ?

**Comment by azheng25** [comment]
This is the exogenous section. 
`exogenous: !VAR1
    rho: 0.9
    Sigma: [[sig_y^2]]
    N: 5`

When I run `@time exog_sim=Dolo.simulate(model.exogenous,500,500)'  the output is: `221.162571 seconds (1.25 G allocations: 79.997 GB, 4.30% gc time)'

**Comment by albop** [comment]
Thanks. The amount of mem. allocation is amazing ! It should be of the same order of magniture as the size of the output.
Looks easy to fixe though. The code has:

```
# Initial conditions
    for i in 1:N
        XN[i, 1, :] = x0
        for jj in 1:N, ii in 1:T-1
            XN[jj, ii+1, :] = var.mu+var.R*(XN[jj, ii, :]-var.mu)+E[jj, ii, :]
        end
    end
    XN = permutedims(XN, [3, 1, 2])
```
which is very inefficient for three reasons:
- it contains a lot of subscrit with respect to the last dimension (i.e. copies of non-consecutive values)
- the is a `permutedim` at the end, meaning that there is no special reason to define arrays as ` zeros(N, T, n)`. They could be declared directly as `zeros(n,N,T)`.
- using this ordering (`n N T`), the computations of `y_{t+1} = rho y_t + e_{t+1}` can be vectorized w.r.t. the two first dimensions `n N`

I totally take the blame for this inefficiency: we didn't know which output ordering to choose at the beginning and I introduced the permutedim as a quickfix.

Who wants to fix it  (i.e. reorder everything as (n,N,T) )? @AnasZa ?

**Comment by AnasZa** [comment]
Sure, I will do that tomorrow if it's not a problem.

**Comment by AnasZa** [comment]
Hey guys, @azheng25 , @albop ) 
 Here is the result. Before to simulate a var as in `test_processes.jl` was taking ` 99.626962 seconds (1.62 G allocations: 81.844 GB, 11.31% gc time)`. Now -   `0.307972 seconds (4.75 M allocations: 209.874 MB, 7.45% gc time)`.  Shall I do a PR?

**Comment by albop** [comment]
Thank you @anasza ! Yes a PR is very welcome.
You haven't said how you did it. Did you just switched the indices or also
vectorized the formulas ?

**Comment by AnasZa** [comment]
I think reordering was not the only issue. The algorithm was inefficient because it was doing the same thing (simulating) NxN times:
```
 for i in 1:N
...
       for jj in 1:N, ii in 1:T-1
...
        end
 end  ```

**Comment by albop** [comment]
Indeed.
