### ISSUE TITLE
Dolo.improved_time_iteration error

### ISSUE THREAD

**Issue by ezgioz** [EconForge/Dolo.jl#117]
> Dolo.improved_time_iteration(model)

gives the error below

> UndefVarError: i not defined

**Comment by albop** [comment]
@ezgioz : do you mean Dolo.imporved_time_iteration(model) ?
@AnasZa : can you fix that one ? I guess it came with PR #115

**Comment by ezgioz** [comment]
@albop yes, Dolo.improved_time_iteration error, edited the issue name accordingly

**Comment by albop** [comment]
I was refering to the content of the issue, actually

**Comment by ezgioz** [comment]
Sorry, yes,  edited the content as well. 

> Dolo.improved_time_iteration(model)

not 

> Dolo.time_iteration(model)
