### ISSUE TITLE
Broken precompile?

### ISSUE THREAD

**Issue by jlperla** [EconForge/Dolo.jl#133]
I did a `Pkg.update()` recently and now `using Dolo` gives
```
WARNING: The call to compilecache failed to create a usable precompiled cache file for module Dolo.
Got:
WARNING: Module Iterators uuid did not match cache file.
ERROR: LoadError: Declaring __precompile__(true) is only allowed in module files being imported.
while loading C:\Users\jlperla\.julia\v0.6\Dolo\src\Dolo.jl, in expression starting on line 1

**Comment by jlperla** [comment]
Any ideas?  Is this an issue with Dolo, Iterators, or my setup?

**Comment by albop** [comment]
I'm not sure. In principle you can't precompile a package (`dolo`) unless all its dependencies (among which `iterators`) are precompiled first. So I guess the issue is with getting the command `Pkd.precompile("Iterators")` to complete. Or you can just disable the precompilation for dolo. Chances are it will give you an actual error somewhere that has nothing to do with precompilation.
If you updated the packages, you can try to restart Julia, just in case. (and if on windows, then restart windows ;-) )

**Comment by albop** [comment]
I just tried on my Linux, and there is no such issue.

**Comment by sglyon** [comment]
This sometimes happens. I haven’t figured out exactly why, but if you restart your Julia and call `using Iterators, Dolo` it should work 

Let us know if it doesn’t

**Comment by sglyon** [comment]
I should add that it sometimes happens with any Julia package and is not specific to dolo. 

I’ve seen this a lot where Julia complains about compat (instead of iterators) when updating random packages (like distributions or statsbase for example)

**Comment by albop** [comment]
Yes I don't think there is something we can do here except add a note in
the doc (or deactivate precompile). Is there a recommended practice to
force precompilation in the right dependency order ?

**Comment by sglyon** [comment]
Because I have seen it when updating various packages, I think this is a bug in Julia and not an issue with something we are doing...

**Comment by albop** [comment]
yeah, but there is a workaround (restart, recompile, try again, in some order), which seems to work. I was wondering, whether there is a clear instruction somewhere for this workaround.

**Comment by jlperla** [comment]
Thanks guys. I will test tonight (unless it also happens on my work
computer).

These exact steps hadn't fixed it last night, though I can try the "using
Iterators" before

**Comment by jlperla** [comment]
Whatever it was , it didn't happen on my work machine and after a `Pkg.update()` it disappeared from my home machine.... Julia....
