### ISSUE TITLE
Transition to 0.7...

### ISSUE THREAD

**Issue by albop** [EconForge/Dolo.jl#140]
Shall we organize a cerenony ?

**Comment by sglyon** [comment]
Haha probably...

I've still been waiting for a few key dependencies (eg distributions.jl) to be stable on 0.7 before trying to get my packages working. 

Maybe we are there now?

**Comment by albop** [comment]
Yes, I haven't tracked the state of our dependencies. We should make a list.
Do you know whether some of the language changes would impact us directly? I'm thinkng about some change in the type system that would screw up our nice decision rule object. I quickly went over the release notes, but didn't see anything striking.

**Comment by sglyon** [comment]
I know there were changes to the AST representation. This might impact some code in Dolang

That's what I can think of off the top of my head

**Comment by albop** [comment]
OK, so then we start with Dolang
