### ISSUE TITLE
Julia 0.5 support

### ISSUE THREAD

**Issue by sglyon** [EconForge/Dolo.jl#17]
The release of 0.5 is imminent. We should work on compatibility soon

**Comment by albop** [comment]
Yes of course. Do you foresee major compatibility issues preventing us from keeping backward compatibility with 0.4 ?

**Comment by spencerlyon2** [comment]
There are some annoyances I tried to work though a bit this afternoon. 

Hopefully there aren't any they can't be resolved using Compat.jl

**Comment by albop** [comment]
Maybe we lost some backward compatibility in the process. 
With Julia 0.4 travis (and my computer) fail with:
```
ERROR: LoadError: LoadError: syntax: missing comma or ) in argument list
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in require at ./loading.jl:259
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/travis/.julia/v0.4/Dolo/src/Dolo.jl, in expression starting on line 51
```

Corresponding line is 
```
_symbol_dict(x) = x
@compat _symbol_dict(d::Associative) =
    Dict{Symbol,Any}(Symbol(k) => _symbol_dict(v) for (k, v) in d)
```

**Comment by spencerlyon2** [comment]
Ahh yes we did mess that up. WE should change it to the following:

```julia
_symbol_dict(x) = x
@compat _symbol_dict(d::Associative) =
    Dict{Symbol,Any}([(Symbol(k) , _symbol_dict(v)) for (k, v) in d])
```

**Comment by albop** [comment]
Given the difference in the ways dimensions are dropped in 0.5, my vote goes to drop compatibility with 0.4 completely.

**Comment by spencerlyon2** [comment]
Excellent. I'm 100% on board with that. I was mostly trying to maintain 0.4 support for you ;)

**Comment by albop** [comment]
I know, I know... Our small user base evolved faster than me ;-) Julia
Professional now has 0.5, and since one can install everything in user
space under Linux, let's indulge ourselves a bit of simplicity...
