### ISSUE TITLE
SymEngine.jl as a replacement for sympy parts of dolo.py

### ISSUE THREAD

**Issue by spencerlyon2** [EconForge/Dolo.jl#18]
SymEngine.jl uses the symengine c++ library (re-write of sympy itself in C++ for better performance). We can hook into this for a symbolic math library for differentiation where needed. 

I have A WIP version of this, but it requires some work to SymEngine.jl itself.

**Comment by albop** [comment]
This is a good idea. As we discussed today there are two options to differentiate functions:
- automatic differentiation (ForwardDiff.jl or http://www.juliadiff.org/)
- symbolic differentiation (SymEngine.jl or Calculus.jl)

The choice of a specific route is a tradeoff between:
- implementation speed (symbolic seems to be easier for multivalues, multivariate functions, and also for higher order differentation)
- numerical stability (used to be a problem with sympy which probably inspired symengine)
- speed (the goal is to be faster than current dynare preprocessor)

**Comment by spencerlyon2** [comment]
I'm going to try using Calculus.jl as a first pass. 

Depending on how long that takes, I'll maybe try SymEngine.jl after that and we can compare speeds.

**Comment by albop** [comment]
This is done in Dolang.
