### ISSUE TITLE
`model_spec` and `model_type`

### ISSUE THREAD

**Issue by spencerlyon2** [EconForge/Dolo.jl#2]
These  should be two methods with specific purposes
- `model_type(::AbstractModel)`: returns one of `:dtcscc`, `:dtmscc` or similar
  `model_spec(::AbstractModel)`: returns a `Vector{Symbol}` that describes the short name for functions that are defined for the model. So something like `[:f, :g, :a]`

**Comment by albop** [comment]
Probably outdated.
