### ISSUE TITLE
dynare_import: comma separated variables are not recognized

### ISSUE THREAD

**Issue by albop** [EconForge/Dolo.jl#22]
In modfiles, variables can be declared in two ways:
- comma-separated as: https://github.com/EconForge/dolo/tree/master/examples/dynare_modfiles/example1.mod
- space-separated as: https://github.com/EconForge/dolo/tree/master/examples/dynare_modfiles/example2.mod

Currently only space-separation works. @jagman88 : do you want to extend the parser you wrote ?

**Comment by spencerlyon2** [comment]
I believe this should be a fairly minor change to the regex used to split variable names.

**Comment by albop** [comment]
We don't aim to import dynare files anymore.
