### ISSUE TITLE
Covariance matrix in the yaml file

### ISSUE THREAD

**Issue by albop** [EconForge/Dolo.jl#33]
@AnasZa found an annoying bug with the way covariance matrices are dealt with: when specifying the covariance matrix of a normal shock in a yaml file, the current behaviour of Dolo.jl is currently inherited from Distributions.MvNormal:

- `sigma: 0.1` translates into the covariance matrix `[[0.01]]`
- `sigma: [0.1, 0.1]` translates in the covariance matrix `[[0.01,0], [0,0.01]`
- `sigma: [[0.01,0], [0,0.01]` is the covariance matrix

Now this is inconsistent with the way yaml files are written (and how dolo.py parses them):

- `sigma: 0.1` is the same as `sigma: [0.1]` is the same as `sigma: [[0.1]]`

I see several ways to resolve the problem:
1/ broadcast the value in the yaml file to a 2d matrix (i.e. choose the python behaviour)
2/ choose and explain the Distributions behaviour and possible write `sig` instead of `sigma` so that it is *less* clear whether it's a vector of a matrix... (as well as make the notation consistent with Distributions).
3/ impose that users always write a matrix in the yaml file, raise an error otherwise
4/ introduce different argument names expecting different types of arguments: `sigma: ` would accept scalar standard deviation, `Sigma` would accept  a matrix only.

Option 1/ and 2/ are both feasible. Which one is best depends on what real people would naturally expect. I would tend to exclude the status quo 1/, but am not too sure about 2/.
Option 3/ is perfectly safe and totally unexciting. Also it doesn't break any existing yaml file.
Option 4/ reintroduces additional flexibility, but in a less canonical way. 

What do other think ?

**Comment by sglyon** [comment]
So, if I understand correctly, we are inconsistent in how we interpret the value of the `sigma` field? Sometimes we treat it as a standard deviation, other times we treat is a vector of standard deviations terms (for independent variables), and other times it is a full covariance matrix?

**Comment by albop** [comment]
Yes, if the user enters a covariance we are consistent. But if he/she enters a scalar or a vector, the way we convert it to a matrix is inconsistent.

**Comment by sglyon** [comment]
Should we just always assume they enter a variance?

So if it is a scalar it is the variance of a 1d Gaussian.

If it is a vector it is the diagonal of a _covariance_ matrix.

**Comment by albop** [comment]
That is exactly what we currently do on the python side (and in existing modfiles). But it's not the convention in Distributions.jl (see above)

**Comment by sglyon** [comment]
I see.

That option has my vote, even if it isn't consistent with Distributions.jl(FWIW I think _their_ behavior is inconsistent)

**Comment by albop** [comment]
Then I propose to rename sigma in Sigma, or optionnally $\Sigma$ . With this form one is less likely to expect it get squared subrepticely. Also, to avoid any ambiguity, let's raise an error if the parameter is not a matrix.
