### ISSUE TITLE
set_calibration method missing

### ISSUE THREAD

**Issue by albop** [EconForge/Dolo.jl#37]
Curently, there isn't a way to change the model calibration once loaded. Based on what we do on the python side, we would expect to be able to do:

`set_calibration(model, :delta, 0.1)`
`set_calibration(model, :delta, :(kappa+0.08) )`
`set_calibration(model, {:delta=>:(kappa+0.08),:alpha=>0.3} )`

with all this methods being equivalent to manually changing the yaml file (except they would be in-memory only).

**Comment by sglyon** [comment]
I believe that these methods

```
setindex!(::FlatCalibration, ...)
setindex!(::GroupedCalibration, ...)
setindex!(::ModelCalibration, ...)
```

should do what you want

**Comment by sglyon** [comment]
If so, it would be very simple to define methods similar to

```julia
set_calibration(m::NumericModel,...) = setindex!(m.calibration, ...)
```

**Comment by albop** [comment]
Problem is not the name of the method, but its behaviour. Unless I missed something I don't think it implements the right behaviour:

```
julia> model.calibration[:delta] = :(k*0.1)
ERROR: MethodError: no method matching _setindex_flat!(::Dolo.ModelCalibration, ::Expr, ::Symbol)
Closest candidates are:
  _setindex_flat!(::Dolo.ModelCalibration, ::Real, ::Symbol) at /home/pablo/.julia/v0.5/Dolo/src/calibration.jl:163
 in setindex!(::Dolo.ModelCalibration, ::Expr, ::Symbol) at /home/pablo/.julia/v0.5/Dolo/src/calibration.jl:173

julia> model.calibration[:delta] = "k*0.1"
ERROR: MethodError: no method matching _setindex_flat!(::Dolo.ModelCalibration, ::String, ::Symbol)
Closest candidates are:
  _setindex_flat!(::Dolo.ModelCalibration, ::Real, ::Symbol) at /home/pablo/.julia/v0.5/Dolo/src/calibration.jl:163
 in setindex!(::Dolo.ModelCalibration, ::String, ::Symbol) at /home/pablo/.julia/v0.5/Dolo/src/calibration.jl:173
```

Instead what should happen is that the symbolic calibration of `delta` should be changed with the value/expression given, and then the calibration of all parameters solved again.

Otherwise, you can easily put the calibrations in an inconsistent state by update one without the other.

**Comment by albop** [comment]
now the `setindex!(::ModelCalibration, ...)` and its parents are perfectly consistent and don't need to be touched.

**Comment by sglyon** [comment]
Got it.

The implementation does do the recursive updating if you set a parameter or variable to a number. I must not have implemented that for setting a parameter to an expression.

**Comment by albop** [comment]
Done as part of the refactoring.
