### ISSUE TITLE
Python->Julia bridge

### ISSUE THREAD

**Issue by albop** [EconForge/Dolo.jl#4]
I just tried:

```
using PyCall
@pyimport dolo

model = dolo.yaml_import("/home/pablo/Programming/econforge/dolo/examples/models/rbc.yaml")
display(model[:calibration])
drp = dolo.approximate_controls(model)
sol = dolo.time_iteration(model, initial_dr=drp)
display(sol)
```

which worked very well 
![screenshot from 2016-04-06 16-45-26](https://cloud.githubusercontent.com/assets/276777/14323072/080d5c20-fc17-11e5-832a-2439d359c3f0.png)

I wonder if we should use that somehow...

**Comment by spencerlyon2** [comment]
This is certainly an interesting option that should work without any problems. PyCall is quite nice.

For me, the main value of having Dolo.jl is to implement algorithms in Julia. For this I want pure Julia functions. 

So the main benefit I see to using PyCall is to bootstrap the parsing (not compiling) stage and potentially give us early access to solution routines already in Python before we come up with the Julia equivalent. 

What are your thoughts? How could this fit in the long run picture?

**Comment by albop** [comment]
In the long run: no place at all. Maybe the other way round if some low-level things work better in Julia that they do in Python.
In the short run we should certainly use it to test conformity and make some timing comparisons with the python side.
I am not sure I get your point about bootstraping the parsing (apart again from cross-testing both sides). One idea would be to keep backward-looking compatible imports only on the python side and not reimplement that in Julia at all.

**Comment by spencerlyon2** [comment]
long run: ok cool, that's what I thought.

The thought about bootstrapping was we could get a Dolo.jl `SymbolicModel` that is 100% compliant with Dolo.py symbolic models today, while the Julia parser is not 100% finished.

I think that having the python bridge would be quite nice for us as developers to have to do the kinds of tests/performance shootouts you described above.

I also like the idea of doing backward compatible changes via the PyCall bridge and letting Dolo.jl focus on the future of the dolo language.

**Comment by albop** [comment]
Since we are close to have smthg working in Julia (and Python master is fairly broken), this is not needed anymore. Cross-language comparisons should be done somewhere else.
