### ISSUE TITLE
Fix travis

### ISSUE THREAD

**Issue by albop** [EconForge/Dolo.jl#43]
Now that some of the API is stabilizing and we are closer to release, we should start to test seriously the package.

**Comment by sglyon** [comment]
I totally agree with this.

At one point (last summer) I had tests for everything in the library. I think we lost that as we made the functionality push over the last 6 months. 

Also I think my original tests have been commented out in the runtests.jl file. As a starting point we can  re-enable those ones.

**Comment by albop** [comment]
Master now passes the tests, thanks to @sglyon
