### ISSUE TITLE
Named/axis arrays for simulations

### ISSUE THREAD

**Issue by albop** [EconForge/Dolo.jl#46]
On the python side, stochastic simulations which are 3d objects are now returned as xarray, i.e. with labelled axes. This turned out to be a great move. IRF are still returned as pandas, although I'm thinking about using xarrays too.
On the Julia side, I would suggest that we do the same with AxisArrays, unless somebody (@sglyon ?) has very strong feeling about NamedArrays.
@AnasZa :  you can have a look at that ? If it looks like a strict improvement, we might want to use that for irfs too.

**Comment by sglyon** [comment]
AxisArray has my vote!

**Comment by AnasZa** [comment]
Yes, I will have a look at it.

**Comment by AnasZa** [comment]
I am not sure to understand the big advantage of naming the arrays. Would't take as many efforts to remember the names as to remember the ordering?

**Comment by albop** [comment]
Well, speaking for myself I don't always remember whether our arrays are NxTxV our `TxNxV`... I also don't know which ordering is more efficient, all things considered. So if we can make the interface indifferent to the ordering or dimensions, that would be nice.
Also, this is not only about naming the dimensions, but also to name the columns, lines, etc.  With DataFrames, you can do `df[:k]` which is easy to remember. But DataFrames, doesn't let you do that for multidim arrays.

**Comment by albop** [comment]
Now in branch https://github.com/EconForge/Dolo.jl/pull/49 the simulations return AxisArray as well. This is also the case for `response` function (it used to return a DataFrame). I wonder whether we should do that too for `tabulate` function and completely get rid of DataFrames.

**Comment by albop** [comment]
Done and merged.
