### ISSUE TITLE
Adding Kronecker products to Dolo

### ISSUE THREAD

**Issue by azheng25** [EconForge/Dolo.jl#57]
Add Kronecker products in the YAML file - e.g. if there are two exogenous shocks `x` and `y`, that follow Markov Chains with transition matrices `Pi_x` and `Pi_y`, respectively, I would like to be able to write `Pi_x` and `Pi_y` separately into the YAML file and have Dolo give me their Kronecker product.

**Comment by albop** [comment]
Right now we have kronecker products of Markov Chains. To do Kronecker products of GDP processes.
