### ISSUE TITLE
Ready-made processes.

### ISSUE THREAD

**Issue by azheng25** [EconForge/Dolo.jl#58]
It would be useful to have certain processes predefined in the YAML file such as an ageing process, a Poisson, and a life-death process.

**Comment by albop** [comment]
Would be useful to define these processes more precisely. Does the following make sense ?
- death (life-death) with proba to die mu
   nodes: [0,1]   (death: 1)
   transition: [[1-mu, mu], [0, 1]]
- aging: with proba to die mu and max age K
   - nodes: [[0,1], [1,0],[2,0]...[K,0]] (first column for age, second column for dead/alive
   - transitions: `p([0,1], [0,1])==1` and `p([i,0], [i+1,0])==(1-mu)`, `p([i,0], [0,1])==mu`, `p([K,0], [0,1])==1`
- poisson:
   - nodes: [0, 1, 2, ..., K]
   - transitions: `p([i], [i]) == (1-mu)`, `p([i], [i+1])==mu`, with `p([K],[K]) ==1

**Comment by albop** [comment]
There is an initial proposal in PR #72. I'd like to merge the PR soon, so you can have a look.
