### ISSUE TITLE
Defining AR1 processes in yaml

### ISSUE THREAD

**Issue by AnasZa** [EconForge/Dolo.jl#59]
At this point, it is not possible to specify different persistent parameters for different AR1 processes in yaml file. To do.

**Comment by albop** [comment]
@AnasZa : do you have an idea how to proceed ?

**Comment by albop** [comment]
There is one case we can deal with: two (several) independent AR1s discretized as Markov Chain. The following should work:
```
exogenous: !Product
   p1: !VAR1
       Sigma: smthg
   p2: !VAR1
      Sigma: smthg_else
```
