### ISSUE TITLE
COMPAT: use of julia >= 0.6- only type keywords

### ISSUE THREAD

**Issue by sglyon** [EconForge/Dolo.jl#62]
Right now we are using `struct` instead of `immutable` to declare the `TimeIterationLog` type. 

This won't work if we still want to support Julia 0.5. Given that JuliaPro is still on 0.5 I think we should continue supporting it.

cc @albop

**Comment by albop** [comment]
Good catch. We need indeed to support 0.5 for now. Thanks for filing this issue.
