### ISSUE TITLE
BUG: getting nx/ns incorrectly in perturbate

### ISSUE THREAD

**Issue by sglyon** [EconForge/Dolo.jl#69]
Instead of

```
    ns = size(g_s, 1)
    nx = size(g_x, 1)
```

I think we should have

```
    ns = size(g_s, 2)
    nx = size(g_x, 2)
```

https://github.com/EconForge/Dolo.jl/blob/455bbe9994632a825b722b61ea1e0cbc03818b2a/src/algos/perturbation.jl#L35-L36

**Comment by albop** [comment]
yes indeed

**Comment by albop** [comment]
It is strange, I remember fixing that one a while ago. Doing it again...
