### ISSUE TITLE
Allowing for changing the size of the shock in Dolo.response function

### ISSUE THREAD

**Issue by AnasZa** [EconForge/Dolo.jl#75]
I realized in algos/simulations.jl there was no option to change the size of the shock. So it would be useful to add smth like :
```
function response(model::AbstractModel,  dr::AbstractDecisionRule,
                  shock_name::Symbol, Impulse::Float64; T::Int=40)
    index_s = findfirst(model.symbols[:exogenous], shock_name)
    e1 = zeros(length(model.calibration[:exogenous]))
    e1[index_s] = Impulse
    s0 = model.calibration[:states]
    response(model, dr, s0, e1; T=T)
end 
```

**Comment by albop** [comment]
Looks like a no-brainer and I'm almost surprised we don't have it already. Can you add it ?

**Comment by AnasZa** [comment]
Ok

**Comment by AnasZa** [comment]
I created a branch: azh/response-shocksize. I added this option plus a description of the response function.

**Comment by albop** [comment]
Can you do a PR ?

**Comment by AnasZa** [comment]
There is still a problem with this merge. It works well for MC models but not for continues exo processes because of evaluate_definitions. When Dolo tries to compute

**Comment by albop** [comment]
My guess is it all boils down to what sim_aa object is at this stage. Is it an AxisArrays with 3d and the axes (N, V, T) ? Does it contain continuous values for all symbols including exogenous vars ?

**Comment by AnasZa** [comment]
This object is the same as in MC case, it includes values for exo, state and control variables, but it doesn't contain the index of states, which is right...
пятница, 30 июня 2017г., 17:39 +01:00 от Pablo Winant  notifications@github.com :
