### ISSUE TITLE
Discretize method options for Product Processes

### ISSUE THREAD

**Issue by azheng25** [EconForge/Dolo.jl#77]
Fix bug to allow user to pass options to the discretize method, when the process is a Product of two subprocesses.

For instance, `discretize(:MarkovChain, Product(p1,p1), arg1, arg2)` which return `MarkovProduct(discretize(:MarkovChain, p1, arg1...), discretize(:MarkovChain, p2, arg2...))`

**Comment by albop** [comment]
@azheng25 : I updated title and content.  We have options to discretize processes. But it currently doesn't work for product processes.
